base_model: gpt2
max_sequence_length: 64
batch_size: 2
accumulation_steps: 4
learning_rate: 2e-5
epochs: 1
device: cuda
max_steps: 0
experiment_type: default  # Options: default, detoxification, emotion_steering, sentiment_steering, language_steering, topic_steering, multi_state_steering
eval_frequency: 50  # How often to run evaluation (in steps)

top_k: 50
top_p: 0.93
temperature: 0.9
max_length: 100
emotion_mapping:
  anger: [1, 0, 0, 0, 0]
  fear: [0, 1, 0, 0, 0]
  joy: [0, 0, 1, 0, 0]
  love: [0, 0, 0, 1, 0]
  sadness: [0, 0, 0, 0, 1]
sentiment_mapping:
  positive: [0,1]
  negative: [1,0]
language_mapping:
  en: [1,0]
  de: [0,1]
topic_mapping:
  gourmet-food: [1,0,0,0,0,0,0,0,0,0]
  video-game: [0,1,0,0,0,0,0,0,0,0]
  clothing: [0,0,1,0,0,0,0,0,0,0]
  beauty: [0,0,0,1,0,0,0,0,0,0]
  arts: [0,0,0,0,1,0,0,0,0,0]
  book: [0,0,0,0,0,1,0,0,0,0]
  jewelry: [0,0,0,0,0,0,1,0,0,0]
  shoe: [0,0,0,0,0,0,0,1,0,0]
  musical-instrument: [0,0,0,0,0,0,0,0,1,0]
  electronics: [0,0,0,0,0,0,0,0,0,1]
multi_state_mapping: 
  book_de: [1,0,1]
  book_en : [0,0,1]             
  book_negative_1 : [0,0,1] 
  book_negative_2 : [0,0,2] 
  book_positive_1 : [0,0,4]
  book_positive_2 : [0,0,5]
  electronics_de: [1,1,1]
  electronics_en : [0,1,1]                      
  electronics_negative_1 : [0,1,1] 
  electronics_negative_2 : [0,1,2] 
  electronics_positive_1 : [0,1,4]
  electronics_positive_2 : [0,1,5]
  clothing_de: [1,2,1]
  clothing_en : [0,2,1]                         
  clothing_negative_1 : [0,2,1]  
  clothing_negative_2 : [0,2,2]  
  clothing_positive_1 : [0,2,4]   
  clothing_positive_2 : [0,2,5]   
  beauty_de: [1,3,1]
  beauty_en : [0,3,1]                         
  beauty_negative_1 : [0,3,1] 
  beauty_negative_2 : [0,3,2] 
  beauty_positive_1 : [0,3,4] 
  beauty_positive_2 : [0,3,5] 

  book_en_1: [0, 0, 1]
  book_en_5: [0, 0, 5]
  electronics_en_1: [0, 1, 1]
  electronics_en_5: [0, 1, 5]
  clothing_en_1: [0, 2, 1]
  clothing_en_5: [0, 2, 5]
  beauty_en_1: [0, 3, 1]
  beauty_en_5: [0, 3, 5]
  book_de_1: [1, 0, 1]
  book_de_5: [1, 0, 5]
  electronics_de_1: [1, 1, 1]
  electronics_de_5: [1, 1, 5]
  clothing_de_1: [1, 2, 1]
  clothing_de_5: [1, 2, 5]
  beauty_de_1: [1, 3, 1]
  beauty_de_5: [1, 3, 5]
  book_en_2: [0, 0, 2]
  book_en_4: [0, 0, 4]
  electronics_en_2: [0, 1, 2]
  electronics_en_4: [0, 1, 4]
  clothing_en_2: [0, 2, 2]
  clothing_en_4: [0, 2, 4]
  beauty_en_2: [0, 3, 2]
  beauty_en_4: [0, 3, 4]
  book_de_2: [1, 0, 2]
  book_de_4: [1, 0, 4]
  electronics_de_2: [1, 1, 2]
  electronics_de_4: [1, 1, 4]
  clothing_de_2: [1, 2, 2]
  clothing_de_4: [1, 2, 4]
  beauty_de_2: [1, 3, 2]
  beauty_de_4: [1, 3, 4]
  negative: [0, 2, 2]
  positive: [0, 2, 4]